---
title: "RWorksheet_Songaling#4b.Rmd"
author: "Charles Daniel Songaling"
date: "2023-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Using Loop Function

#1. Using the for loop, create an R script that will display a 5x5 matrix as shown in Figure 1. It must contain vectorA = [1,2,3,4,5] and a 5 x 5 zero matrix.

vectorA <- c(1,2,3,4,5)

matrixA <- matrix ((0),5,5)
  
  for(i in 1:5)
    for(j in 1:5)
  
  matrixA[i,j] <- abs(vectorA[i] - vectorA[j])
  matrixA
``` 
```{r}  
#2. Print the string "*" using for() function. The output should be the same as shown in Figure 1.

  for(i in 1:5)
    
      
```
```{r}
#3. Get an input from the user to print the Fibonacci sequence starting from the 1st input up to 500. Use repeat and break statements. Write the R Scripts and its output.


```
Using Basic Graphics (plot(),barplot(),pie(),hist())
```{r}
#4. Import the dataset as shown in Figure 1 you have created previously.

  #a. What is the R script for importing an excel or a csv file? Display the first 6 rows of the dataset? Show your codes and its result.
  
  Household_data <- data.frame(
    Shoe_size =c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
    
    Height =c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
    
    Gender =c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
  )
  Household_data
  write.csv(Household_data)
  
  #b. Create a subset for gender(female and male). How many observations are there in Male? How about in Female? Write the R scripts and its output.



```